name: Build and Test

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up QEMU
      run: |
        sudo apt-get update
        sudo apt-get install -y qemu-system-x86
        
    - name: Set up GCC cross-compiler
      run: |
        sudo apt-get install -y gcc-multilib gcc-multilib-i386-linux-gnu
        
    - name: Build project
      run: |
        make clean
        make
        
    - name: Test build artifacts
      run: |
        ls -la *.img
        file kernel
        
    - name: Run basic tests
      run: |
        echo "Build completed successfully"
        echo "Project structure:"
        find . -name "*.c" -o -name "*.h" | head -10
        
  lint:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Install cppcheck
      run: sudo apt-get install -y cppcheck
      
    - name: Run static analysis
      run: |
        find . -name "*.c" -exec cppcheck --enable=all --error-exitcode=1 {} \;
        
  documentation:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Check documentation
      run: |
        echo "Checking README.md..."
        if [ ! -f README.md ]; then
          echo "ERROR: README.md not found"
          exit 1
        fi
        
        echo "Checking LICENSE..."
        if [ ! -f LICENSE ]; then
          echo "ERROR: LICENSE not found"
          exit 1
        fi
        
        echo "Documentation check passed"
